example_app/main/routes.py
import os
import pandas as pd

from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required

from example_app import photos, db
from example_app.main.forms import ProfileForm
from example_app.models import Profile, Region
from my_flask_app.models import User

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    img_list = []
    for filename in os.listdir('static/images/logos'):
        img_list.append(filename)
    img_df = pd.DataFrame(img_list, columns=['filename'])
    img_df['year'] = img_df['filename'].str[:4]
    img_df['event'] = img_df['filename'].str[5:-4]
    if not current_user.is_anonymous:
        name = current_user.first_name
        flash(f'Hello {name}. ')
    img_df.sort_values(by=['year'], inplace=True)
    img_df.reset_index(inplace=True, drop=True)
    images = img_df.values.tolist()
    return render_template('index.html', title='Home page', images=images)


@main_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    profile = Profile.query.join(User, User.id == Profile.user_id).filter(User.id == current_user.id).first()
    if profile:
        return redirect(url_for('main.update_profile'))
    else:
        return redirect(url_for('main.create_profile'))


@main_bp.route('/create_profile', methods=['GET', 'POST'])
@login_required
def create_profile():
    form = ProfileForm()
    form.region_id.choices = [(r.id, r.region) for r in Region.query.order_by('region')]
    print(len(form.region_id.choices))
    if request.method == 'POST' and form.validate_on_submit():
        # Set the filename for the photo to None, this is the default if the user hasn't chosen to add a profile photo
        filename = None
        if 'photo' in request.files:
            if request.files['photo'].filename != '':
                # Save the photo using the global variable photos to get the location to save to
                filename = photos.save(request.files['photo'])
        p = Profile(region_id=form.region_id.data, username=form.username.data, photo=filename, bio=form.bio.data,
                    user_id=current_user.id)
        db.session.add(p)
        db.session.commit()
        return redirect(url_for('main.display_profiles', username=p.username))
    return render_template('profile.html', form=form)


@main_bp.route('/update_profile', methods=['GET', 'POST'])
@login_required
def update_profile():
    profile = Profile.query.join(User, User.id == Profile.user_id).filter_by(id=current_user.id).first()
    # https://wtforms.readthedocs.io/en/3.0.x/fields/#wtforms.fields.SelectField fields with dynamic choice
    form = ProfileForm(obj=profile)
    form.region_id.choices = [(r.id, r.region) for r in Region.query.order_by('region')]
    if request.method == 'POST' and form.validate_on_submit():
        if 'photo' in request.files:
            filename = photos.save(request.files['photo'])
            profile.photo = filename
        profile.region = form.region_id.data
        profile.bio = form.bio.data
        profile.username = form.username.data
        db.session.commit()
        return redirect(url_for('main.display_profiles', username=profile.username))
    return render_template('profile.html', form=form)


@main_bp.route('/display_profiles', methods=['POST', 'GET'], defaults={'username': None})
@main_bp.route('/display_profiles/<username>/', methods=['POST', 'GET'])
@login_required
def display_profiles(username):
    results = None
    if username is None:
        if request.method == 'POST':
            term = request.form['search_term']
            if term == "":
                flash("Enter a name to search for")
                return redirect(url_for("main.index"))
            results = Profile.query.filter(Profile.username.contains(term)).all()
    else:
        results = Profile.query.filter_by(username=username).all()
    if not results:
        flash("Username not found.")
        return redirect(url_for("main.index"))
    urls = []
    for result in results:
        if result.photo:
            url = photos.url(result.photo)
            urls.append(url)
    return render_template('display_profile.html', profiles=zip(results, urls))

example_app/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field( **kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

example_app/templates/display_profile.html
{% extends 'layout.html' %}
{% set title = 'Profile Display' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    {% for result, url in profiles %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{ url }}" alt="User profile photo">
            <div class="card-body">
                <h5 class="card-title">{{ result.username }}</h5>
                <h6>{{ result.area }}</h6>
                <p class="card-text">{{ result.bio }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

example_app/templates/index.html
{% extends 'layout.html' %}
{% block content %}
    {% for img in images %}
        <div class="float-start p-2 mx-3 text-center">
            <img height=100 id="img-{{ img[2] }}-{{ img[1] }}" src="{{ url_for('static', filename='images/logos/') }}{{ img[0] }}"
                 alt="{{ img[2] }} {{ img[1] }}">
            <p>{{ img[1] }}</p>
            <p>{{ img[2] }}</p>

        </div>
    {% endfor %}
{% endblock %}

example_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
            integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous"
            async></script>
    <title>{{ title }}</title>
    {% block extra_tags %}{% endblock %}
</head>
<body>
<header class="container-fluid">
    <br>
    {% include 'navbar.html' %}
</header>
<div id="flash-messages">
    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <p class="alert alert-info" role="alert">{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
<main>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>
</body>
</html>

example_app/templates/login.html
{% extends 'layout.html' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <form method=post action="{{ url_for('auth.login') }}">
        {{ form.csrf_token }}
        {{ render_field(form.email, class="form-control") }}
        {{ render_field(form.password, class="form-control") }}
        {{ render_field(form.remember, class="form-check-input") }}
    <p><button type="submit" class="btn btn-primary">Login</button></p>
    </form>
{% endblock %}

example_app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">ParalympicResults</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("main.index") }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Profiles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/dashboard/">Dashboard</a>
                </li>
                {# Shows/hides login, signup and logout depending on status #}
                {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.login") }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.signup") }}">Sign up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("main.profile") }}">MyProfile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">Logout</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{{ url_for("main.display_profiles") }}" method="post">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                       name="search_term">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

example_app/templates/profile.html
{% extends 'layout.html' %}
{% set title = 'Profile' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.username, class="form-control") }}
            {{ render_field(form.bio, class="form-control") }}
            {{ render_field(form.region_id, class="form-control") }}
            {{ render_field(form.photo, class="custom-file", id="input_file") }}

        </dl>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

example_app/templates/signup.html
{% extends 'layout.html' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}

    {# Version using _formhelpers see: https://flask.palletsprojects.com/en/2.0.x/patterns/wtforms/#forms-in-templates #}
    <form method=post action="{{ url_for('auth.signup') }}">
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.first_name, class="form-control") }}
            {{ render_field(form.last_name, class="form-control") }}
            {{ render_field(form.email, class="form-control") }}
            {{ render_field(form.password, class="form-control") }}
            {{ render_field(form.password_repeat, class="form-control") }}
        </dl>
        <p><button type="submit" class="btn btn-primary">Sign up</button></p>
    </form>

    {# This version doesn't use the _formhelpers
    <form method="POST" action="{{ url_for('auth.signup') }}" class="row g3">
        {{ form.csrf_token }}
        <div class="col-md-6">
            {{ form.first_name.label(class='form-label') }} {{ form.first_name(class='form-control') }}
        </div>
        <div class="col-md-6">
            {{ form.last_name.label(class='form-label') }} {{ form.last_name(class='form-control') }}
        </div>
        <div class="col-md-12">
            {{ form.email.label(class='form-label') }} {{ form.email(class='form-control') }}
        </div>
        <div class="col-md-6">
            {{ form.password.label(class='form-label') }} {{ form.password(class='form-control') }}
        </div>
        <div class="col-md-6">
            {{ form.password_repeat.label(class='form-label') }} {{ form.password_repeat(class='form-control') }}
        </div>
        <div class="col-12">
            <br>
            <button type="submit" class="btn btn-primary">Sign up</button>
        </div>
    </form>
    #}

{% endblock %}